// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCatalogWebApplication.Data;

#nullable disable

namespace eCatalogWebApplication.Migrations
{
    [DbContext(typeof(eCatalogWebApplicationContext))]
    partial class eCatalogWebApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eCatalogWebApplication.Models.Catalog", b =>
                {
                    b.Property<int>("IDCatalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCatalog"));

                    b.Property<string>("NameCatalog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCatalog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCatalog");

                    b.ToTable("Catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
